### ISSUE TITLE
Re-fork repositories to avoid confusion

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/EasyClip-Extension#10]
@JuliaLopinto To avoid confusion, could you delete your project `JuliaLopinto/EasyClip-Extension` and re-fork the one hosted in the `DCBIA-OrthoLab` organization. See https://github.com/DCBIA-OrthoLab/EasyClip-Extension

The fork graph currently shows this:

![image](https://user-images.githubusercontent.com/219043/70097620-cbe35480-15f7-11ea-837f-f456415e8837.png)

@fbudin69500 : Could you do the same ?

Thanks :pray:

**Comment by jcfr** [comment]
Ping

**Comment by jcfr** [comment]
Ping

**Comment by JuliaLopinto** [comment]
it's done for me :)

**Comment by jcfr** [comment]
@fbudin69500 Could you take care of this one as well ?

**Comment by jcfr** [comment]
Ping @fbudin69500

**Comment by allemangD** [comment]
I have contacted github support in the past to disconnect the upstream a forked repo; perhaps that is an option here.

**Comment by jcfr** [comment]
Closing. Repository has been re-forked.
